//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Script/ShootingGame/ShootingControl.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ShootingControl: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ShootingControl()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ShootingControl"",
    ""maps"": [
        {
            ""name"": ""Dragging"",
            ""id"": ""3d45111b-b169-4a86-af63-2f453fab2aa1"",
            ""actions"": [
                {
                    ""name"": ""Look"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f170595f-3606-44ca-8e01-6f6a476354b8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f0121092-7632-412c-a535-d4acd5d6f67e"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Dragging
        m_Dragging = asset.FindActionMap("Dragging", throwIfNotFound: true);
        m_Dragging_Look = m_Dragging.FindAction("Look", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Dragging
    private readonly InputActionMap m_Dragging;
    private List<IDraggingActions> m_DraggingActionsCallbackInterfaces = new List<IDraggingActions>();
    private readonly InputAction m_Dragging_Look;
    public struct DraggingActions
    {
        private @ShootingControl m_Wrapper;
        public DraggingActions(@ShootingControl wrapper) { m_Wrapper = wrapper; }
        public InputAction @Look => m_Wrapper.m_Dragging_Look;
        public InputActionMap Get() { return m_Wrapper.m_Dragging; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DraggingActions set) { return set.Get(); }
        public void AddCallbacks(IDraggingActions instance)
        {
            if (instance == null || m_Wrapper.m_DraggingActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DraggingActionsCallbackInterfaces.Add(instance);
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
        }

        private void UnregisterCallbacks(IDraggingActions instance)
        {
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
        }

        public void RemoveCallbacks(IDraggingActions instance)
        {
            if (m_Wrapper.m_DraggingActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDraggingActions instance)
        {
            foreach (var item in m_Wrapper.m_DraggingActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DraggingActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DraggingActions @Dragging => new DraggingActions(this);
    public interface IDraggingActions
    {
        void OnLook(InputAction.CallbackContext context);
    }
}
