//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Script/TankShooter/TankInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @TankInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @TankInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""TankInput"",
    ""maps"": [
        {
            ""name"": ""HoldScreen"",
            ""id"": ""61cc5c66-73a4-4a12-b40e-09878f0105c4"",
            ""actions"": [
                {
                    ""name"": ""End"",
                    ""type"": ""PassThrough"",
                    ""id"": ""8c61ad0a-ebd8-4f8a-bba1-145aaa6d8631"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Start"",
                    ""type"": ""PassThrough"",
                    ""id"": ""dc6064cc-294f-4389-9ab9-f94f7547f948"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(pressPoint=0.01)"",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ad6a7d27-517f-4a7d-9a0c-a0ef012ca4ee"",
                    ""path"": ""<Touchscreen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""End"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aa992c1b-6bfa-4277-85b1-471f097efb92"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // HoldScreen
        m_HoldScreen = asset.FindActionMap("HoldScreen", throwIfNotFound: true);
        m_HoldScreen_End = m_HoldScreen.FindAction("End", throwIfNotFound: true);
        m_HoldScreen_Start = m_HoldScreen.FindAction("Start", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // HoldScreen
    private readonly InputActionMap m_HoldScreen;
    private List<IHoldScreenActions> m_HoldScreenActionsCallbackInterfaces = new List<IHoldScreenActions>();
    private readonly InputAction m_HoldScreen_End;
    private readonly InputAction m_HoldScreen_Start;
    public struct HoldScreenActions
    {
        private @TankInput m_Wrapper;
        public HoldScreenActions(@TankInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @End => m_Wrapper.m_HoldScreen_End;
        public InputAction @Start => m_Wrapper.m_HoldScreen_Start;
        public InputActionMap Get() { return m_Wrapper.m_HoldScreen; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(HoldScreenActions set) { return set.Get(); }
        public void AddCallbacks(IHoldScreenActions instance)
        {
            if (instance == null || m_Wrapper.m_HoldScreenActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_HoldScreenActionsCallbackInterfaces.Add(instance);
            @End.started += instance.OnEnd;
            @End.performed += instance.OnEnd;
            @End.canceled += instance.OnEnd;
            @Start.started += instance.OnStart;
            @Start.performed += instance.OnStart;
            @Start.canceled += instance.OnStart;
        }

        private void UnregisterCallbacks(IHoldScreenActions instance)
        {
            @End.started -= instance.OnEnd;
            @End.performed -= instance.OnEnd;
            @End.canceled -= instance.OnEnd;
            @Start.started -= instance.OnStart;
            @Start.performed -= instance.OnStart;
            @Start.canceled -= instance.OnStart;
        }

        public void RemoveCallbacks(IHoldScreenActions instance)
        {
            if (m_Wrapper.m_HoldScreenActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IHoldScreenActions instance)
        {
            foreach (var item in m_Wrapper.m_HoldScreenActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_HoldScreenActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public HoldScreenActions @HoldScreen => new HoldScreenActions(this);
    public interface IHoldScreenActions
    {
        void OnEnd(InputAction.CallbackContext context);
        void OnStart(InputAction.CallbackContext context);
    }
}
